language: php

php:
  - 5.4

mysql:
  database: data_starter
  username: root
  encoding: utf8

install:
  - mysql -e 'create database data_starter;'
  - sudo apt-get update > /dev/null
  - sudo apt-get --quiet=2 install php5-cgi php5-curl php5-gd php5-mysql > /dev/null

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:dev-master
  - composer global require --no-interaction youngj/httpserver:*
  
  # Install DKAN
  - git clone https://github.com/NuCivic/dkan.git
  - cd dkan
  - git checkout 7.x-1.6
  - drush make build-dkan.make docroot
  - cd docroot
  - drush si dkan --sites-subdir=default --db-url=mysql://root:@127.0.0.1:3306/dkan_travis --account-name=admin --account-pass=admin  --site-name="DKAN" install_configure_form.update_status_module='array(FALSE,FALSE)' --yes
  - drush cc all --yes
  - drush --quiet --yes --root=$PWD runserver :8888 > /dev/null 2>&1 &
  - sleep 4

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

  - cd ..
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - java -jar selenium-server-standalone-2.42.2.jar -quiet -p 4444 -log shut_up_selenium &
  - sleep 5

script:
  # Initial test
  - cd test
  - composer install
  - bin/behat features/search.feature
  - cd ../../.
  
  # Run rebuild 
  - sh rebuild_dkan_core.sh -t 7.x-1.x -d $PWD/dkan/docroot
  
  # Secondary test
  - cd dkan/test
  - bin/behat features/search.feature
